packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of components/
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"

# 定义目录和依赖版本号
catalog:
  lodash-es: ^4.17.21
  axios: ^1.7.8
  better-sqlite3: 11.9.0
  font-ls: 0.6.0
  ntsuspend: ^1.0.2
  mitt: ^3.0.1
